name: Deploy Infrastructure and Configure Servers

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'ansible/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'ansible/**'

jobs:
  terraform_and_ansible:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.0.11"  # Especifique a versão do Terraform se necessário

    - name: Terraform Init
      run: terraform -chdir=terraform init

    - name: Terraform Plan
      run: terraform -chdir=terraform plan -var "ami=${{ secrets.AMI }}" -var "vpc_id=${{ secrets.VPC_ID }}" -var "subnet_id=${{ secrets.SUBNET_ID }}" -var "igw_id=${{ secrets.IGW_ID }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    - name: Terraform Apply
      run: terraform -chdir=terraform apply -auto-approve -var "ami=${{ secrets.AMI }}" -var "vpc_id=${{ secrets.VPC_ID }}" -var "subnet_id=${{ secrets.SUBNET_ID }}" -var "igw_id=${{ secrets.IGW_ID }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
     
    - name: Create SSH Key File
      run: |
        echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > $HOME/.ssh/ansible_key
        chmod 600 $HOME/.ssh/ansible_key

    - name: Set up Python for Ansible
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run Ansible Playbook
      run: ansible-playbook -i ansible/hosts ansible/playbooks/site.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
        ANSIBLE_PRIVATE_KEY_FILE: $HOME/.ssh/ansible_key
